# Deep Learning {#deep-learning}

* Neural networks based on stacking various layers of neurons.
* World of feature embeddings, transfer learning and foundation models.
* A machine learning mindset, can also be used for [supervised learning](#supervised-ml).




* Language Models
  * powerful connector of tasks and concepts
  * the importance of a prompt
  * any knowledge is hidden somewhere in the embeddings
* Vision Models


* Special case of risk-based mindset
* It's own mindset because
  * transfer learning. Especially foundation models.
  * feature learning
  * modularity
  * universe of its own. like only using lego to play.
  * Some people would only use neural network
  * universal function approximator
  * any ml model can be distilled into neural network
* Called deep learning instead of neural networks, because it's about how we learn about the world
* Optimization does not matter really
* especially works for images and text
* prediction-focused
*

## Neural Networks

* a bit about architecture


## Transfer Learning


Combine different models: SM Socrates models: https://arxiv.org/pdf/2204.00598.pdf

## Advantages

## Limitations

* Adversarial attacks

References:

* List of pre-trained models https://huggingface.co/models
