# Nonparametric Statistics

Check intro from: http://erecursos.uacj.mx/bitstream/handle/20.500.11961/2064/Gibbons%2C%202003.pdf?sequence=14
Nonparametric means that we don't make assumption of some parameterized distribution.
Our goal is NOT to find the best parameters for some distribution.

Also in another sense is nonparametric statistics different:
We assume, in general, less fixed structure for our model.
Think linear model with fixed structure vs. a generalized additive model where the individual components can be smooth.


Nonparametric statistic still needs parameters.
some methods really do without parameter.
Like the median.
Or some tests.
But some parts of nonparametric statistics needs even more parameters.
Like splines.
Nonparametric is more in the sense that our attention is no longer on the parameters that describe the distribution.

Can only be used in combination with other mindsets of frequentist or Bayesian stats.

"[Nonparametric problems]" typically involve fewer assumptions of structure and distributional form but" - David Cox, p2. of Principls of Statistical Inference
usually contain strong assumptions about independencies.

Some methods:

* Median
* Histogram, kernel density estimation
* Some descriptive statistics such as cohens kappa
* Non-parametric tests
* non-parametric models such as LOESS
* Bootstrap and friends to compute confidence intervals
* splines? GAMs?
*

## Bootstrap

I think bootstrap here is one central idea, that shows that nonparametric statistic is its own mindset.

TODO: Is bootstrap really based on sound theory?


## Advantages

* Statistics but with less explicit distributional assumptions necessary
* In some parts more intuitive
*



## Limitations

* Compared to frequentist and Bayesian stats, we also loose some interpretability
* We need more parameters to describe distribution 
* Often come with stronger assumptions about independent of the data


## References:

* https://biostat.jhsph.edu/~mmccall/articles/efron_1991.pdf
* https://en.wikipedia.org/wiki/Nonparametric_statistics
* Cox: Principles of Statistical Inference file:///Users/chris/Downloads/Principles_of_Statistical_Inference.pdf
