# Preface


Preface: inspired by two cultutes by breiman.  Praise for breiman. I learned frequentism. Mind opening when I learned about machine learning. And Leo's paper. Bur there are even more cultures.

how this book came about

some anecdotes from my life


You find many books and essays on

- frequentist vs. bayesianism
- ml vs stats
- causal vs. frequentist

Also when teaching happens, at least in my teaching I think different mindsets should have been made clearer.

For example, I think that distribution-free statistics is very different from likelihood-based mindset.


TODO: Write about my own journey:

* studied frequentist
* also worked a lot with frequentist stats
* learned a bit about bayesian and machine learning
* later self-taught a lot of machine learning
* worked as frequentist
* worked as machine learner
* did phd in interpretable machine learning
* self-taught on causality
* had one frequentist project where causality mindset saved the project
* learned a lot from Bayesian podcast


I studied statistics.
It was almost purely the likelihood-based frequentist mindsets.
We did have a bit of Bayesian statistics, nonparametric statistics and machine learning.
Later on I dove deep into machine learning, so that my two primary mindsets are frequentism and supervised machine learning.
But I also made some strides into causality.

